SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PM].[Companies](
	[CRNNO] [int] NOT NULL,
	[CompanyName] [varchar](50) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [PM].[Companies] ADD PRIMARY KEY CLUSTERED 
(
	[CRNNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
